services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: builtadi-app:latest
    container_name: builtadi-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - builtadi

  nginx:
    image: nginx:1.25-alpine
    container_name: builtadi-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - builtadi

  db:
    image: mysql:8.0
    container_name: builtadi-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-builtadi}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-builtadi}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    networks:
      - builtadi

networks:
  builtadi:
    driver: bridge
